url: https://sanduni-p.github.io/docker-intro/
project:
  type: website

website:
  title: "Introduction to Docker"
  navbar:
    left:
      - href: index.html
        text: Home
      - text: Workshop Materials
        menu:
          - text: Introducing Containers
            href: episodes/01-introduction.qmd
          - text: Introducing the Docker Command Line
            href: episodes/02-meet-docker.qmd
          - text: Exploring and Running Containers
            href: episodes/03-running-containers.qmd
          - text: Cleaning Up Containers
            href: episodes/04-managing-containers.qmd
          - text: Finding Containers on Docker Hub
            href: episodes/05-docker-hub.qmd
          - text: Creating Your Own Container Images
            href: episodes/06-creating-container-images.qmd
          - text: Creating More Complex Container Images
            href: episodes/07-advanced-containers.qmd
          - text: Examples of Using Container Images in Practice
            href: episodes/08-docker-image-examples.qmd
          - text: "Containers in Research Workflows: Reproducibility and Granularity"
            href: episodes/09-reproduciblity.qmd
        

format:
  html:
    theme: 
      - cerulean
      - utils/css/custom.scss
    toc: true
    toc-expand: 1
    toc-title: Contents
    embed-resources: true
    css: utils/css/custom.css
    smooth-scroll: true
    df-print: kable
execute: 
  freeze: auto
jupyter: python3   

metadata-files:
  - _variables.yml

resources:
    - episodes/files/docker-intro.zip